### ISSUE TITLE
提醒：Windows下使用"pip install -r requirements.txt"默认安装为CPU版本的torch

### ISSUE THREAD

**Issue by Golevka2001** [chenfei-wu/TaskMatrix#171]
清华镜像源中的 torch 只有 CPU 版本的，即使在 pytorch 网页上复制了正确的命令行。

解决办法：

1. pip 切换为默认源或其他没有此问题的镜像源;

2. 直接到 https://download.pytorch.org/whl/torch_stable.html 手动下载 CUDA 版本。

**Comment by loner233** [comment]
我的环境：
![Screenshot_20230314_192855](https://user-images.githubusercontent.com/16119486/224987906-1fa1e021-79f4-49cc-92a0-6e1735d7e221.png)


通过清华源安装pytorch
![Screenshot_20230314_192708](https://user-images.githubusercontent.com/16119486/224987616-0dac1952-6c46-4e6e-b2e2-fb6e3265892c.png)

看上去没什么问题啊
![Screenshot_20230314_192727](https://user-images.githubusercontent.com/16119486/224987745-70e3cf1d-a685-45c6-ad3f-5a39e4af13b7.png)

**Comment by Golevka2001** [comment]
或许是我自己机器的问题，描述的不太准确，我这里复现了一下。

Windows 平台。

1. 直接 `pip install` ，这里安装 torch 默认的是 cpu 版本的：
![Snipaste_2023-03-14_19-51-06](https://user-images.githubusercontent.com/101185502/224997718-e4bd7f5e-a910-4fe1-be0e-2e65520a80e8.png)
找不到 `torch==1.12.1+cu113` 的包：
![Snipaste_2023-03-14_20-18-21](https://user-images.githubusercontent.com/101185502/224999339-9f476c53-9260-4a71-bc96-c3713845c5e9.png)


2. 之后从 pytorch 官网复制命令下载，成功下载到了 CUDA 版本（可能当时操作有误）。但下载源来自 pytorch，清华源中找不到该包：
![Snipaste_2023-03-14_20-19-00](https://user-images.githubusercontent.com/101185502/224999985-5abccaba-3975-4a94-8b89-82f87683eefd.png)

**Comment by loner233** [comment]
不应该是清华源的问题

https://pypi.org/project/torch/1.12.1/#files 
我看上去pypi上面的1.12.1的windows版的pytorch只有100多MB，linux版的大小比windows的大了几倍

好像pypi的上pytorch发布的wheel，Windows版的都只有这么大，可能Windows都只发了CPU版吧

一直用的linux，头一次发现这个，不过这个问题倒是和这个repo没啥关系。

**Comment by GuoqiangW** [comment]
我在windows下直接pip install -r requirements.txt装的是cpu版本，建议直接从pytorch装
pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116

**Comment by nagaki09** [comment]
> 

我一旦执行pip install -r requirements.txt 后，conda list里面就找不到 pytorch了，这个命令为啥会这样啊？有什么别的解决方案吗

**Comment by Golevka2001** [comment]
> > 
> 
> 我一旦执行pip install -r requirements.txt 后，conda list里面就找不到 pytorch了，这个命令为啥会这样啊？有什么别的解决方案吗

1. 是否在同一个环境下执行的 `pip install` 和 `conda list` 命令？
2. 在 list 中的名字是 ***torch***，是否漏看？

**Comment by nagaki09** [comment]
> 
windows下装的torch估计是cpu的版本，之后启动的时候，一直提示Torch not compiled with CUDA enabled的错误

**Comment by Rain2022debug** [comment]
```
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge
```
同样报CUDA不兼容的错误，参考Pytorch官网命令解决了。
链接：https://pytorch.org/get-started/previous-versions/

**Comment by hksanduo** [comment]
个人特例，遇到朋友可以参考一下，本人使用的镜像是nvidia/cuda:11.8.0-devel-ubuntu22.04 + conda，conda配置了tuna的镜像源，在安装过程中即使指定了pytorch的channel，conda安装的pytorch版本默认为cpu版本，尝试以下方案，包括：移除cpu版本组件，pytorch-mutex等，均未生效，最后将tuna channel注释掉，指定pytorch channel解决了这个问题。

**Comment by mimin123dai** [comment]
我安装了 官网的 命令 失败了  换镜像源 和别的 都不起 效果  但后来成功了 成功猜测如下
1 我没有安装pytorch 最新版本的  命令 我找到了之前的pytorch 版本 https://pytorch.org/get-started/previous-versions/
2  换了镜像源 conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
conda config --set show_channel_urls yes
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/
□ 然后输入命令行：
conda install pytorch torchvision torchaudio pytorch-cuda=版本 -c nvidia

猜想如下  会不会是最新的 命令行和 镜像源冲突 导致的
